server:
  port: 8094
  servlet:
    context-path: /movies
  
spring:
  application:
    name: movies-service

  datasource:
   # url: jdbc:mysql://localhost:3306/clinicServiceDataBase?createDatabaseIfNotExist=true
    #url: jdbc:mysql://localhost:3306/appointmentServiceDataBase?createDatabaseIfNotExist=true
    url: jdbc:mysql://db.ccb27u4ngh0j.ap-south-1.rds.amazonaws.com:3306/movies?createDatabaseIfNotExist=true
    #username: root
    #password: 1234
    #url: jdbc:mysql://db.ccb27u4ngh0j.ap-south-1.rds.amazonaws.com:3306/appoinmentopt?createDatabaseIfNotExist=true 
    username: admin 
    password: qwerty12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
     ddl-auto: create
    properties:
     hibernate:
            database-platform: org.hibernate.dialect.MySQL8Dialect
           
swagger:
     productionURL: https://movies.learn.skillassure.com/movies
     #localURL: https://localhost:${server.port}/appointment

  

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://service.learn.skillassure.com/eureka/
  instance:
    hostname: service.learn.skillassure.com

logging:
  file:
    name: inventory.log`
  pattern:
    console: '%d %-5level %logger : %msg%n'
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    '[org.springframework.web]': INFO
    '[com.ros.inventory]': DEBUG
    '[org.hibernate]': INFO
